{{- if or .Values.extraSecretEnvs (not .Values.externalSecret.ncDb.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nocodb.fullname" . }}
  labels:
    {{- include "nocodb.labels" . | nindent 4 }}
data:
  {{- if not .Values.externalSecret.ncDb.enabled }}
  NC_DB: {{ include "databaseUri" . | b64enc}}
  {{- end }}
{{- range $key, $value := .Values.extraSecretEnvs }}
  {{ $key }}: '{{ $value | b64enc }}'
{{- end }}
{{- end }}